# main.yml
---
- name: search running appclusters
  shell: ps -aef | egrep "java.*{{ item.cluster_name }}" | grep -v grep
  register: app_proc_search
  loop:
    "{{ appclusters }}"
  ignore_errors: yes
  tags:
    - stop
    - restart
    - start
    - check

- name: define appclusters is running
  set_fact:
    appclusters_state: 'running'
  when:
    ( item.rc == 0 )
  loop:
    "{{ app_proc_search.results }}"
  tags:
    - stop
    - restart
    - start
    - check

- name: define appclusters is stopped
  set_fact:
    appclusters_state: 'stopped'
  when:
    ( item.rc == 1 )
  loop:
    "{{ app_proc_search.results }}"
  tags:
    - stop
    - restart
    - start
    - check
...
