# main.yml
---
- name: create directory for ansible scripts
  file:
    path: "{{ ansible_scripts_directory }}"
    state: directory
    mode: '0775'
    unsafe_writes: yes
  tags:
    - stop
    - restart
    - start
    - check
    - appclusters

- name: create dmgr script
  template:
    src: "wsadmin_manage_appclusters.py.j2"
    dest: "{{ ansible_scripts_directory }}/wsadmin_manage_appclusters.py"
    follow: yes
    mode: 0644
    newline_sequence: "\n"
    owner: "{{ websphere.os_user }}"
    group: "{{ websphere.os_group }}"
  tags:
    - stop
    - restart
    - start
    - check
    - appclusters

- name: check appclusters
  shell: "{{ websphere_profiles_path}}/{{ dmgr_profile_name }}/bin/wsadmin.sh \
    -lang jython -username {{ dmgr_bus_user }} -password {{ dmgr_bus_password }} \
    -f {{ ansible_scripts_directory }}/wsadmin_manage_appclusters.py check"
  no_log: True
  register: appcl_check_result
  ignore_errors: yes
  failed_when:
    ( appcl_check_result.rc != 0
    and appcl_check_result.rc != 105 )
  tags:
    - stop
    - restart
    - start
    - check
    - appclusters


- name: define appclusters is running
  set_fact:
    appclusters_state: 'running'
  when:
    ( appcl_check_result.stdout is search(' cluster is running!') )
  tags:
    - stop
    - restart
    - start
    - check
    - appclusters

- name: define appclusters is stopped
  set_fact:
    appclusters_state: 'stopped'
  when:
    ( appcl_check_result.stdout is search(' cluster is stopped!')
    or appcl_check_result.stdout is search('AdminTask object is not available.') )
  tags:
    - stop
    - restart
    - start
    - check
    - appclusters
...
